name: 'template_expressions'
description: 'A Dart library to process string based templates using expressions.'
homepage: 'https://github.com/peiffer-innovations/template_expressions'
version: '3.2.0'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  intl: '^0.18.0'
  meta: '^1.9.0'
  petitparser: '^6.0.0'
  quiver: '^3.0.0'

dev_dependencies:
  flutter_lints: '^3.0.1'
  test: '^1.25.2'
